name: API Documentation

on:
  release:
    types: [published]
  #workflow_dispatch:

jobs:
  build_docs:
    runs-on: [self-hosted, docs]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ethz-msrl/Tesla_core
          lfs: true
          token: ${{ secrets.NAVION_MSRL_READ_TOKEN }}
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      - name: Build docker image
        run: |
          docker build . -f docker/Dockerfile-docs --tag tsc-docs
      - name: Remove old docs
        run: rm -rf ../docs
      - name: Create docs folder
        run: mkdir ../docs
      - name: Build docs
        run: |
          docker run --name tsc-docs \
          tsc-docs bash -c "catkin clean -y && catkin build && \
          rosrun tsc_utils generate_docs.py -o /docs /tc_ws/src/Tesla_core"
      - name: Copy docs from docker
        run: docker cp tsc-docs:/docs ..
      - name: Remove docker container
        run: docker rm tsc-docs
      - name: Copy docs to web server
        run: |
          rm -rf /var/www/tesla-docs/tesla_core/${{ steps.get_release.outputs.tag_name }} && \
          cp -r ../docs /var/www/tesla-docs/tesla_core/${{ steps.get_release.outputs.tag_name }}
