name: prerelease

on: 
  push: 
    branches:
      - 'releases/**'
jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/releases/v}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: false
        token: ${{ secrets.CLANG_FORMAT_PAT }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install catkin_pkg
    - name: Update version number
      run: python |
        $GITHUB_WORKSPACE/tsc_utils/scripts/update_version_number.py $GITHUB_WORKSPACE $RELEASE_VERSION
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: MSRL GitHub Robot
        author_email: msrl.gh-robot@ethz.ch
        message: "Commiting version number changes"

  update_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Set release version
      # note that this release version keeps the v in it
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/releases/}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: false
        token: ${{ secrets.CLANG_FORMAT_PAT }}
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install dependencies
      run: |
        gem install github_changelog_generator
    - name: Update changelog
      run: github_changelog_generator -u ethz-msrl -p Tesla_core -t ${{ secrets.GITHUB_TOKEN }} --future-release $RELEASE_VERSION
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: MSRL GitHub Robot
        author_email: msrl.gh-robot@ethz.ch
        message: "Commiting changelog changes"
