# Snapcraft Build and Upload
# Uses Tesla_core branch defined in snap.rosinstall and, therefore, independent of current PR until merged with master.
# This means that this one can not be used as a PR test. It is just creating the latest snap.

name: snapcraft_build_and_publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ethz-msrl/Navion
        ref: master
        token: ${{ secrets.NAVION_MSRL_READ_TOKEN }}
    - run: |
        sed -i 's|git@github\.com:|https://${{ secrets.NAVION_MSRL_READ_TOKEN }}@github\.com/|g' $GITHUB_WORKSPACE/snap/local/snap.rosinstall
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAP_STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge        
    - run: |
        cd $GITHUB_WORKSPACE
        snapcraft clean
        lxc delete snapcraft-navion
